[project]
name = "smart-prisoners"
version = "0.1.0"
description = "Prisoner problem solver"
authors = [
    {name = "BenScherrer",email = "ben.scherrer59@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "polars (>=1.31.0,<2.0.0)",
    "ipykernel (>=6.29.5,<7.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
